### ISSUE TITLE
Is this the evolution of your python-based openstack-seeder ?

### ISSUE THREAD

**Issue by alistarle** [sapcc/openstack-seeder#1]
Hi folks,

I see this repo look like the openstack-seeder directory in your kubernetes-operator project: https://github.com/sapcc/kubernetes-operators/tree/master/openstack-seeder, is this a rewriting in go and should we rely on this one instead of the python one ?

Really great job about Openstack orchestration over Kube, glad to contribute to add more resource to be handled :)

**Comment by stefanhipfel** [comment]
Hi, 
we tried to rewrite it in go, but gophercloud unfortunately does not support the whole openstack api. So we decided to write it completely in python: seeder and operator [seeder-ccloud](https://github.com/sapcc/seeder-ccloud).
Since it is also supposed to seed other resource than openstack, it was renamed :)

But enhancing the openstack resources is always welcome! :)

btw it is still work in progress
